#!/data/data/com.termux/files/usr/bin/bash
# Created by Tej hacker
cd /data/data/com.termux/files/usr/bin/
rm toolss
cd $HOME/Termux-Toolss
mv toolss /data/data/com.termux/files/usr/bin/
cd /data/data/com.termux/files/usr/bin/bash
chmod +x toolss
clear
